### ISSUE TITLE
Add sample serviceAccount.json and bitlyAccount.json

### ISSUE THREAD

**Issue by soleo** [ebidel/perftools-runner#1]
The repo didn't include any instruction for `serviceAccount.json` and `bitlyAccount.json` which are needed for running the app

**Comment by radum** [comment]
Bitly is easy, generate your token and then add this content to the file:

```
{
	"accessToken": "value here"
}
```

As for serviceAccount.json that is from Google cloud https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#createanewserviceaccount

**Comment by ebidel** [comment]
Yea sorry about this. I didn't have enough time pre-Google I/O to fully round out the documentation. If anyone wants to submit a PR to add these to the readme, happy to review it.
